name: Deploy Python App to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest stable version

      - name: Set up Python
        uses: actions/setup-python@v3  # Use the latest stable version
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Connect to EC2 and execute commands
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to the application directory
            cd /home/ubuntu/Python-EC2-GitHub-Actions || exit
            
            
        # Pull latest changes from the repository
            git pull origin main || exit
            
        # Install dependencies inside the virtual environment
            python3 -m pip install --upgrade pip || exit
            pip install -r requirements.txt || exit

        # Kill any previous running Flask app
            pkill -f app.py || exit

            # Run Flask app in the background within the virtual environment
            nohup python3 app.py &  # Run Flask app in the background
          EOF

      - name: Deployment complete
        run: |
          echo "Deployment Complete!"
